import { NextResponse } from "next/server";
import * as XLSX from "xlsx";
import { requireStaff } from "../../../lib/requireStaff";
import { REPORTS, reportList } from "../../../lib/reports";

// Admin only, checked server-side. Several of these carry salary, full
// financial history and patient contact details, so the check cannot live in
// the interface alone - the route has to refuse on its own.
async function requireAdmin(req) {
  const staff = await requireStaff(req);
  if (!staff) return { error: NextResponse.json({ error: "Sign in first." }, { status: 401 }) };
  if (staff.role !== "admin") {
    return { error: NextResponse.json({ error: "Exports are restricted to admins." }, { status: 403 }) };
  }
  return { staff };
}

export async function GET(req) {
  const { error, staff } = await requireAdmin(req);
  if (error) return error;

  const url = new URL(req.url);
  const key = url.searchParams.get("report");

  if (!key) return NextResponse.json({ reports: reportList() });

  const report = REPORTS[key];
  if (!report) return NextResponse.json({ error: "No such report." }, { status: 404 });

  const today = new Date().toISOString().slice(0, 10);
  const from = url.searchParams.get("from") || `${today.slice(0, 4)}-01-01`;
  const to = url.searchParams.get("to") || today;
  const period = url.searchParams.get("period") || "";
  const format = url.searchParams.get("format") === "csv" ? "csv" : "xlsx";
  const preview = url.searchParams.get("preview") === "1";

  let rows;
  try {
    rows = await report.rows({ from, to, period });
  } catch (e) {
    return NextResponse.json({ error: `Could not build that report: ${e.message}` }, { status: 500 });
  }

  // A preview shows the shape and the row count before committing to a
  // download, so nobody opens a file to discover it is empty.
  if (preview) {
    return NextResponse.json({ count: rows.length, sample: rows.slice(0, 8), columns: rows[0] ? Object.keys(rows[0]) : [] });
  }

  if (!rows.length) {
    return NextResponse.json({ error: "Nothing to export for that period." }, { status: 404 });
  }

  const stamp = report.dated ? `${from}_to_${to}` : today;
  const filename = `${key}_${stamp}`;

  if (format === "csv") {
    const ws = XLSX.utils.json_to_sheet(rows);
    const csv = XLSX.utils.sheet_to_csv(ws);
    // Excel reads a UTF-8 CSV as the local codepage unless it sees a BOM, which
    // turns every Arabic name into mojibake.
    return new NextResponse("\uFEFF" + csv, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}.csv"`,
      },
    });
  }

  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.json_to_sheet(rows);

  // Column widths from the content, so a spreadsheet does not open as a wall of
  // ### and truncated names.
  const cols = Object.keys(rows[0]);
  ws["!cols"] = cols.map((c) => {
    const longest = rows.reduce((m, r) => Math.max(m, String(r[c] ?? "").length), c.length);
    return { wch: Math.min(Math.max(longest + 2, 10), 45) };
  });
  // Autofilter on the header. Freeze panes are a paid SheetJS feature, so the
  // filter is what carries the usability of a long sheet here.
  ws["!autofilter"] = { ref: ws["!ref"] };

  XLSX.utils.book_append_sheet(wb, ws, report.label.slice(0, 30));

  // A second sheet records what this file is and who pulled it, so a
  // spreadsheet found later can still be traced and dated.
  const meta = [
    { Field: "Report", Value: report.label },
    { Field: "Description", Value: report.description },
    { Field: "Period", Value: report.dated ? `${from} to ${to}` : period || "All time" },
    { Field: "Rows", Value: rows.length },
    { Field: "Generated", Value: new Date().toISOString().replace("T", " ").slice(0, 19) },
    { Field: "Generated by", Value: staff.name || staff.email || "" },
    { Field: "Source", Value: "Al Shrooouk Scan & Lab platform" },
  ];
  const metaWs = XLSX.utils.json_to_sheet(meta);
  metaWs["!cols"] = [{ wch: 16 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, metaWs, "About");

  const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
  return new NextResponse(buf, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${filename}.xlsx"`,
    },
  });
}
